//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVisitorMSEntities : DbContext
    {
        public DBVisitorMSEntities()
            : base("name=DBVisitorMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EPDetail> EPDetails { get; set; }
        public DbSet<EPMaster> EPMasters { get; set; }
        public DbSet<DODetail> DODetails { get; set; }
        public DbSet<DOMaster> DOMasters { get; set; }
        public DbSet<NewsMaster> NewsMasters { get; set; }
    }
}
