//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMaster
    {
        public DOMaster()
        {
            this.DODetails = new HashSet<DODetail>();
        }
    
        public System.Guid MasterId { get; set; }
        public int SENo { get; set; }
        public string DONo { get; set; }
        public string UseDep { get; set; }
        public string UseID { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string Address { get; set; }
        public string DelVia { get; set; }
        public string DriName { get; set; }
        public string VechNo { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedPic { get; set; }
        public string SecurityCheck { get; set; }
        public string SecurityPic { get; set; }
        public Nullable<bool> ManagerApprove { get; set; }
        public string Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<DODetail> DODetails { get; set; }
    }
}
