//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DODetail
    {
        public System.Guid DetailId { get; set; }
        public System.Guid MasterId { get; set; }
        public int Id { get; set; }
        public string Product { get; set; }
        public int Quantity { get; set; }
        public string Remark { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<System.DateTime> ReturnedBy { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string Photo { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DOMaster DOMaster { get; set; }
    }
}
