//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsMaster
    {
        public System.Guid MasterId { get; set; }
        public string NewsId { get; set; }
        public string Header { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> Viewer { get; set; }
        public string BodyTEXT { get; set; }
        public string BodyHTML { get; set; }
        public string FeaturedImage { get; set; }
    }
}
