//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPDetail
    {
        public System.Guid DetailId { get; set; }
        public System.Guid MasterId { get; set; }
        public string UseID { get; set; }
        public int Id { get; set; }
    
        public virtual EPMaster EPMaster { get; set; }
    }
}
