//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPMaster
    {
        public EPMaster()
        {
            this.EPDetails = new HashSet<EPDetail>();
        }
    
        public System.Guid MasterId { get; set; }
        public int SENo { get; set; }
        public string EPNo { get; set; }
        public string UseDep { get; set; }
        public string PlantID { get; set; }
        public string Destination { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Out { get; set; }
        public System.TimeSpan In { get; set; }
        public bool CompTrans { get; set; }
        public Nullable<System.TimeSpan> CompTransTime { get; set; }
        public string Status { get; set; }
        public Nullable<System.TimeSpan> ActOut { get; set; }
        public Nullable<System.TimeSpan> ActIn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<EPDetail> EPDetails { get; set; }
    }
}
